-- SQL Case Study 1: Gaurav Singh (grv08singh@gmail.com)

CREATE DATABASE case_study1;
USE case_study1;

SELECT * FROM [dbo].[fact];
SELECT * FROM [dbo].[Location];
SELECT * FROM [dbo].[Product];


-- Problem Statement:
-- You are a database administrator. You want to use the data to answer a few
-- questions about your customers, especially about the sales and profit coming
-- from different states, money spent in marketing and various other factors such as
-- COGS (Cost of Goods Sold), budget profit etc. You plan on using these insights
-- to help find out which items are being sold the most. You have been provided
-- with the sample of the overall customer data due to privacy issues. But you hope
-- that these samples are enough for you to write fully functioning SQL queries to
-- help answer the questions.

-- Dataset:
-- The 3 key datasets for this case study:
-- a. FactTable: The Fact Table has 14 columns mentioned below and 4200
-- rows. Date, ProductID, Profit, Sales, Margin, COGS, Total Expenses,
-- Marketing, Inventory, Budget Profit, Budget COGS, Budget Margin, Budget
-- Sales, and Area Code
-- Note: COGS stands for Cost of Goods Sold

-- b. ProductTable: The ProductTable has four columns named Product Type,
-- Product, ProductID, and Type. It has 13 rows which can be broken down
-- into further details to retrieve the information mentioned in theFactTable.

-- c. LocationTable: Finally, the LocationTable has 156 rows and follows a
-- similar approach to ProductTable. It has four columns named Area Code,
-- State, Market, and Market Size.


-- Tasks to be performed:
-- 1. Display the number of states present in the LocationTable.
SELECT * FROM [dbo].[Location];
SELECT COUNT(DISTINCT([State])) AS State_Count FROM [dbo].[Location];


-- 2. How many products are of regular type?
SELECT * FROM [dbo].[Product];
SELECT COUNT([Product_Type]) FROM [dbo].[Product] WHERE [Type] = 'Regular';


-- 3. How much spending has been done on marketing of product ID 1?
SELECT * FROM [dbo].[fact];
SELECT SUM([Marketing]) FROM [dbo].[fact] WHERE [ProductId] = 1;



-- 4. What is the minimum sales of a product?
SELECT * FROM [dbo].[Product];
SELECT MIN([Sales]) FROM [dbo].[fact];
SELECT * FROM [dbo].[fact] WHERE [Sales] = (SELECT MIN([Sales]) FROM [dbo].[fact]);

-- 5. Display the max Cost of Good Sold (COGS).
SELECT MAX(COGS) AS max_cogs FROM [dbo].[fact];



-- 6. Display the details of the product where product type is coffee.
SELECT * FROM [dbo].[Product] WHERE [Product_Type] = 'Coffee';



-- 7. Display the details where total expenses are greater than 40.
SELECT * FROM [dbo].[fact] WHERE [Total_Expenses] > 40;



-- 8. What is the average sales in area code 719?
SELECT AVG([Sales]) AS avg_sales_719 FROM [dbo].[fact] WHERE [Area_Code] = 719;



-- 9. Find out the total profit generated by Colorado state.
SELECT SUM([Profit]) AS colorado_profit FROM [dbo].[fact] f
INNER JOIN [dbo].[Location] l
ON f.[Area_Code] = l.[Area_Code]
WHERE l.[State] = 'Colorado';



-- 10. Display the average inventory for each product ID.
SELECT [ProductId],AVG([Inventory]) AS avg_inventory FROM [dbo].[fact]
GROUP BY [ProductId];



-- 11. Display state in a sequential order in a Location Table.
SELECT DISTINCT [State] FROM [dbo].[Location] ORDER BY [State] ASC;



-- 12. Display the average budget of the Product where the average budget
-- margin should be greater than 100.
SELECT [ProductId], AVG([Budget_Profit]) AS avg_budget, AVG([Budget_Margin]) AS avg_bud_margin 
FROM [dbo].[fact] GROUP BY [ProductId] HAVING AVG([Budget_Margin]) > 100;



-- 13. What is the total sales done on date 2010-01-01?
SELECT SUM([Sales]) AS total_sales FROM [dbo].[fact] WHERE [Date] = '2010-01-01';



-- 14. Display the average total expense of each product ID on an individual date.
SELECT [Date], [ProductId], AVG([Total_Expenses]) FROM [dbo].[fact] GROUP BY [Date], [ProductId];



-- 15. Display the table with the following attributes such as date, productID,
-- product_type, product, sales, profit, state, area_code.
SELECT f.date, f.productID,p.product_type, p.product, f.sales, f.profit, l.state, f.area_code
FROM [dbo].[fact] f
JOIN [dbo].[Product] p
ON f.[ProductId] = p.[ProductId]
JOIN [dbo].[Location] l
ON f.[Area_Code] = l.[Area_Code];
-- INNER JOIN is default.



-- 16. Display the rank without any gap to show the sales wise rank.
-- Windows functions: rank, dense_rank, rownumber
SELECT [Date], [ProductId], [Sales],
DENSE_RANK() OVER (ORDER BY [Sales] DESC) AS sales_rank
FROM [dbo].[fact];



-- 17. Find the state wise profit and sales.
SELECT l.[State], SUM(f.[Profit]) AS profit, SUM(f.[Sales]) AS sales FROM [dbo].[fact] f
JOIN [dbo].[Location] l
ON f.[Area_Code] = l.[Area_Code]
GROUP BY l.[State];



-- 18. Find the state wise profit and sales along with the product name.
SELECT l.[State], p.[Product], SUM(f.[Profit]) AS profit, SUM(f.[Sales])  AS sales FROM [dbo].[fact] f
JOIN [dbo].[Location] l
ON f.[Area_Code] = l.[Area_Code]
JOIN [dbo].[Product] p
ON f.[ProductId] = p.[ProductId]
GROUP BY l.[State], p.[Product];



-- 19. If there is an increase in sales of 5%, calculate the increased sales.
SELECT *, [Sales]*1.05 AS inc_sales FROM [dbo].[fact];



-- 20. Find the maximum profit along with the product ID and producttype.
SELECT f.[ProductId], p.[Product_Type], f.[Profit]
FROM [dbo].[fact] f
JOIN [dbo].[Product] p
ON f.[ProductId] = p.[ProductId]
WHERE f.[Profit] = (SELECT MAX([Profit]) FROM [dbo].[fact]);



-- 21. Create a stored procedure to fetch the result according to the product type
-- from Product Table.
-- system defined procedure
sp_help Product;

-- user defined procedure
DROP PROCEDURE sp_GetProductType;

CREATE PROCEDURE sp_GetProductType @ProductType VARCHAR(30)
AS
BEGIN
	SELECT * FROM [dbo].[Product] WHERE [Product_Type] = @ProductType
END;


EXEC sp_GetProductType 'Coffee';
EXEC sp_GetProductType 'Espresso';
EXEC sp_GetProductType 'Herbal Tea';




-- 22. Write a query by creating a condition in which if the total expenses is less than
-- 60 then it is a profit or else loss.
SELECT * FROM [dbo].[fact];

SELECT *, 
CASE
	WHEN [Total_Expenses] < 60 THEN 'Profit'
	ELSE 'Loss'
END AS Profit_Loss
FROM [dbo].[fact];



-- 23. Give the total weekly sales value with the date and product ID details. Use
-- roll-up to pull the data in hierarchical order.
SELECT DATEPART(YEAR, [Date]) AS YEAR,
DATEPART(WEEK, [Date]) AS WEEK,
[ProductId],
SUM([Sales]) AS WEEKLY_SALES
FROM [dbo].[fact]
GROUP BY ROLLUP(DATEPART(YEAR, [Date]), DATEPART(WEEK, [Date]), [ProductId]);





-- 24. Apply union and intersection operator on the tables which consist of
-- attribute area code.
SELECT [Area_Code] FROM [dbo].[fact]
UNION
SELECT [Area_Code] FROM [dbo].[Location];


SELECT [Area_Code] FROM [dbo].[fact]
INTERSECT
SELECT [Area_Code] FROM [dbo].[Location];


SELECT [Area_Code] FROM [dbo].[fact]
EXCEPT
SELECT [Area_Code] FROM [dbo].[Location];



-- 25. Create a user-defined function for the product table to fetch a particular
-- product type based upon the user’s preference.
DROP FUNCTION fq_ProductType;

CREATE FUNCTION fq_ProductType(@Type VARCHAR(30))
RETURNS TABLE
AS
	RETURN
	SELECT * FROM [dbo].[Product] WHERE [Product_Type] = @Type;

SELECT * FROM fq_ProductType('Tea');



-- 26. Change the product type from coffee to tea where product ID is 1 and undo
-- it.
BEGIN TRAN
BEGIN TRANSACTION
UPDATE [dbo].[Product] SET [Product_Type]='Tea' WHERE [ProductId]=1;
ROLLBACK

SELECT * FROM [dbo].[Product];



-- 27. Display the date, product ID and sales where total expenses are
-- between 100 to 200.
SELECT [Date], [ProductId], [Sales] FROM [dbo].[fact] WHERE [Total_Expenses] BETWEEN 100 AND 200;



-- 28. Delete the records in the Product Table for regular type.
SELECT * FROM [dbo].[Product];

BEGIN TRANSACTION
DELETE FROM [dbo].[Product] WHERE [Type]='Regular';
ROLLBACK



-- 29. Display the ASCII value of the fifth character from the columnProduct.
SELECT [Product],SUBSTRING([Product],5,1),ASCII(SUBSTRING([Product],5,1)) AS ascii_5th_char FROM [dbo].[Product];


